import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const figtree = localFont({
  src: "./fonts/Figtree-VariableFont_wght.ttf",
  variable: "--font-figtree",
  weight: "500 800",
});
const figtreeItalic = localFont({
  src: "./fonts/Figtree-Italic-VariableFont_wght.ttf",
  variable: "--font-figtree-italic",
  weight: "500 800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${figtreeItalic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
